const $ = document.querySelector.bind(document);
const $$ = document.querySelectorAll.bind(document);
sanpham = $(".ProductJS");
footerCategory = $(".footer__category--table");

// product
const products = {
  product: [
    {
      name: "ÁO THUN NAM NGẮN TAY CỔ BẺ MẪU MỚI NHIỀU MÀU",
      image: "assests/img/clothes/1_1.jpg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp2.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo chống nắng nam chất xước thời trang nam Menswear , áo khoác chống nắng nam mẫu mới cải tiến che phủ cao.",
      image: "./assests/img/product/sp3.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp4.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo chống nắng nam chất xước thời trang nam Menswear , áo khoác chống nắng nam mẫu mới cải tiến che phủ cao.",
      image: "./assests/img/product/sp5.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo sơ mi basic chất kaki cao cấp, Áo sơ mi nam cực đẹp [AKC]",
      image: "./assests/img/product/sp6.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp7.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo chống nắng nam chất xước thời trang nam Menswear , áo khoác chống nắng nam mẫu mới cải tiến che phủ cao.",
      image: "./assests/img/product/sp8.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp9.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo sơ mi basic chất kaki cao cấp, Áo sơ mi nam cực đẹp [AKC]",
      image: "./assests/img/product/sp10.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp11.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo sơ mi nam trơn vải kate lụa mịn LADOS - 25779 chất vải thấm hút tốt - Form chuẩn công sở",
      image: "./assests/img/product/sp12.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp13.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo chống nắng nam chất xước thời trang nam Menswear , áo khoác chống nắng nam mẫu mới cải tiến che phủ cao.",
      image: "./assests/img/product/sp14.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo sơ mi nam trơn vải kate lụa mịn LADOS - 25779 chất vải thấm hút tốt - Form chuẩn công sở",
      image: "./assests/img/product/sp15.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo sơ mi basic chất kaki cao cấp, Áo sơ mi nam cực đẹp [AKC]",
      image: "./assests/img/product/sp16.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo sơ mi nam trơn vải kate lụa mịn LADOS - 25779 chất vải thấm hút tốt - Form chuẩn công sở",
      image: "./assests/img/product/sp17.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp18.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo giữ nhiệt nam tay dài ôm body co giãn 4 chiều đẹp cao cấp VN87B",
      image: "./assests/img/product/sp19.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo sơ mi basic chất kaki cao cấp, Áo sơ mi nam cực đẹp [AKC]",
      image: "./assests/img/product/sp20.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp21.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp22.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp23.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo sơ mi nam trơn vải kate lụa mịn LADOS - 25779 chất vải thấm hút tốt - Form chuẩn công sở",
      image: "./assests/img/product/sp24.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp25.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp26.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo sơ mi basic chất kaki cao cấp, Áo sơ mi nam cực đẹp [AKC]",
      image: "./assests/img/product/sp27.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo giữ nhiệt nam tay dài ôm body co giãn 4 chiều đẹp cao cấp VN87B",
      image: "./assests/img/product/sp28.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp29.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo sơ mi basic chất kaki cao cấp, Áo sơ mi nam cực đẹp [AKC]",
      image: "./assests/img/product/sp30.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp31.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo giữ nhiệt nam tay dài ôm body co giãn 4 chiều đẹp cao cấp VN87B",
      image: "./assests/img/product/sp32.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp33.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo sơ mi nam dài tay KJ chất vải lụa thái phom vừa người tôn dáng chống bai xù phong cách công sở KJ-Vua Quần Jeans",
      image: "./assests/img/product/sp34.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo sơ mi basic chất kaki cao cấp, Áo sơ mi nam cực đẹp [AKC]",
      image: "./assests/img/product/sp35.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp36.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo sơ mi nam dài tay KJ chất vải lụa thái phom vừa người tôn dáng chống bai xù phong cách công sở KJ-Vua Quần Jeans",
      image: "./assests/img/product/sp37.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp38.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp39.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo sơ mi nam dài tay KJ chất vải lụa thái phom vừa người tôn dáng chống bai xù phong cách công sở KJ-Vua Quần Jeans",
      image: "./assests/img/product/sp41.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp42.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo sơ mi basic chất kaki cao cấp, Áo sơ mi nam cực đẹp [AKC]",
      image: "./assests/img/product/sp43.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo sơ mi nam dài tay KJ chất vải lụa thái phom vừa người tôn dáng chống bai xù phong cách công sở KJ-Vua Quần Jeans",
      image: "./assests/img/product/sp44.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp45.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo sơ mi nam trơn vải kate lụa mịn LADOS - 25779 chất vải thấm hút tốt - Form chuẩn công sở",
      image: "./assests/img/product/sp46.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo sơ mi nam dài tay KJ chất vải lụa thái phom vừa người tôn dáng chống bai xù phong cách công sở KJ-Vua Quần Jeans",
      image: "./assests/img/product/sp47.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      image: "./assests/img/product/sp48.jpeg",
      price: "50.000",
      sold: "6",
    },
    {
      name: "Áo sơ mi nam trơn vải kate lụa mịn LADOS - 25779 chất vải thấm hút tốt - Form chuẩn công sở",
      image: "./assests/img/product/sp49.jpeg",
      price: "50.000",
      sold: "6",
    },
  ],
};

// category--selling--bottom
const html = products.product.map((item, index) => {
  return ` 
  <div class="col l-2 m-3 c-6 suggest__product">
  <a href="" class="home-product-item">
  <img src="${item.image}" alt="" class="home-product-item__img"> 
      <h4 class="home-product-item__name">${item.name}</h4>
      <div class="home-product-item__price">
          <span class="home-product-item__price-old">1.200.000đ</span>
          <span class="home-product-item__price-curent">${item.price}đ</span>
      </div>
      <div class="home-product-item__action">
          <span class="home-product-item__like home-product-item__like--liked">
              <i class="home-product-item__like-icon-empty fa-regular fa-heart"></i>
              <i class="home-product-item__like-icon-fill fa-solid fa-heart"></i>
          </span>
          <div class="home-product-item__rating">
              <i class="home-product-item__star--gold fa-solid fa-star"></i>
              <i class="home-product-item__star--gold fa-solid fa-star"></i>
              <i class="home-product-item__star--gold fa-solid fa-star"></i>
              <i class="home-product-item__star--gold fa-solid fa-star"></i>
              <i class=" fa-solid fa-star"></i>
          </div>
          <span class="home-product-item__sold">${item.sold} đã bán</span>
      </div>

      <div class="home-product-item__origin">
          <span class="home-product-item__brand">Who</span>
          <span class="home-product-item__origin-name">Nhật bản</span>
      </div>
      <div class="home-product-item__favourite">
          <i class="fa-solid fa-check"></i>
          <span>Yêu thích</span>
      </div>
      <div class="home-product-item__sale-off">
          <span class="home-product-item__sale-off-percent">43%</span>
          <span class="home-product-item__sale-off-label">GIẢM</span>
      </div>
  </a>
  <div class="home-product-similar">
      tìm sản phẩm tương tự
  </div>
</div>
  `;
});

sanpham.innerHTML = html.join("");

// footer--category
const category = {
  listCategory: [
    {
      title: "THỜI TRANG NAM,",
      things: [
        "Áo Khoác | ",
        "Áo Vest và Blazer | ",
        "Áo Hoodie, Áo Len & Áo Nỉ | ",
        "Quần Jeans | ",
        "Quần Dài/Quần Âu | ",
        "Quần Short | ",
        "Áo | ",
        "Áo Ba Lỗ | ",
        "Đồ Lót | ",
        "Đồ Ngủ | ",
        "Đồ Bộ | ",
        "Vớ/Tất | ",
        "Trang Phục Truyền Thống | ",
        "Đồ Hóa Trang | ",
        "Trang Phục Ngành Nghề | ",
        "Khác | ",
        "Trang Sức Nam | ",
        "Kính Mắt Nam | ",
        "Thắt Lưng Nam | ",
        "Cà vạt & Nơ cổ | ",
        "Phụ Kiện Nam | ",
      ],
    },
    {
      title: "THỜI TRANG NU,",
      things: [
        "Áo Khoác | ",
        "Áo Vest và Blazer | ",
        "Áo Hoodie, Áo Len & Áo Nỉ | ",
        "Quần Jeans | ",
        "Quần Dài/Quần Âu | ",
        "Quần Short | ",
        "Áo | ",
        "Áo Ba Lỗ | ",
        "Đồ Lót | ",
        "Đồ Ngủ | ",
        "Đồ Bộ | ",
        "Vớ/Tất | ",
        "Trang Phục Truyền Thống | ",
        "Đồ Hóa Trang | ",
        "Trang Phục Ngành Nghề | ",
        "Khác | ",
        "Trang Sức Nam | ",
        "Kính Mắt Nam | ",
        "Thắt Lưng Nam | ",
        "Cà vạt & Nơ cổ | ",
        "Phụ Kiện Nam | ",
      ],
    },
    {
      title: "THỜI TRANG NU,",
      things: [
        "Áo Khoác | ",
        "Áo Vest và Blazer | ",
        "Áo Hoodie, Áo Len & Áo Nỉ | ",
        "Quần Jeans | ",
        "Quần Dài/Quần Âu | ",
        "Quần Short | ",
        "Áo | ",
        "Áo Ba Lỗ | ",
        "Đồ Lót | ",
        "Đồ Ngủ | ",
        "Đồ Bộ | ",
        "Vớ/Tất | ",
        "Trang Phục Truyền Thống | ",
        "Đồ Hóa Trang | ",
        "Trang Phục Ngành Nghề | ",
        "Khác | ",
        "Trang Sức Nam | ",
        "Kính Mắt Nam | ",
        "Thắt Lưng Nam | ",
        "Cà vạt & Nơ cổ | ",
        "Phụ Kiện Nam | ",
      ],
    },
    {
      title: "THỜI TRANG NU,",
      things: [
        "Áo Khoác | ",
        "Áo Vest và Blazer | ",
        "Áo Hoodie, Áo Len & Áo Nỉ | ",
        "Quần Jeans | ",
        "Quần Dài/Quần Âu | ",
        "Quần Short | ",
        "Áo | ",
        "Áo Ba Lỗ | ",
        "Đồ Lót | ",
        "Đồ Ngủ | ",
        "Đồ Bộ | ",
        "Vớ/Tất | ",
        "Trang Phục Truyền Thống | ",
        "Đồ Hóa Trang | ",
        "Trang Phục Ngành Nghề | ",
        "Khác | ",
        "Trang Sức Nam | ",
        "Kính Mắt Nam | ",
        "Thắt Lưng Nam | ",
        "Cà vạt & Nơ cổ | ",
        "Phụ Kiện Nam | ",
      ],
    },
    {
      title: "THỜI TRANG NU,",
      things: [
        "Áo Khoác | ",
        "Áo Vest và Blazer | ",
        "Áo Hoodie, Áo Len & Áo Nỉ | ",
        "Quần Jeans | ",
        "Quần Dài/Quần Âu | ",
        "Quần Short | ",
        "Áo | ",
        "Áo Ba Lỗ | ",
        "Đồ Lót | ",
        "Đồ Ngủ | ",
        "Đồ Bộ | ",
        "Vớ/Tất | ",
        "Trang Phục Truyền Thống | ",
        "Đồ Hóa Trang | ",
        "Trang Phục Ngành Nghề | ",
        "Khác | ",
        "Trang Sức Nam | ",
        "Kính Mắt Nam | ",
        "Thắt Lưng Nam | ",
        "Cà vạt & Nơ cổ | ",
        "Phụ Kiện Nam | ",
      ],
    },
    {
      title: "THỜI TRANG NAM,",
      things: [
        "Áo Khoác | ",
        "Áo Vest và Blazer | ",
        "Áo Hoodie, Áo Len & Áo Nỉ | ",
        "Quần Jeans | ",
        "Quần Dài/Quần Âu | ",
        "Quần Short | ",
        "Áo | ",
        "Áo Ba Lỗ | ",
        "Đồ Lót | ",
        "Đồ Ngủ | ",
        "Đồ Bộ | ",
        "Vớ/Tất | ",
        "Trang Phục Truyền Thống | ",
        "Đồ Hóa Trang | ",
        "Trang Phục Ngành Nghề | ",
        "Khác | ",
        "Trang Sức Nam | ",
        "Kính Mắt Nam | ",
        "Thắt Lưng Nam | ",
        "Cà vạt & Nơ cổ | ",
        "Phụ Kiện Nam | ",
      ],
    },
    {
      title: "THỜI TRANG NU,",
      things: [
        "Áo Khoác | ",
        "Áo Vest và Blazer | ",
        "Áo Hoodie, Áo Len & Áo Nỉ | ",
        "Quần Jeans | ",
        "Quần Dài/Quần Âu | ",
        "Quần Short | ",
        "Áo | ",
        "Áo Ba Lỗ | ",
        "Đồ Lót | ",
        "Đồ Ngủ | ",
        "Đồ Bộ | ",
        "Vớ/Tất | ",
        "Trang Phục Truyền Thống | ",
        "Đồ Hóa Trang | ",
        "Trang Phục Ngành Nghề | ",
        "Khác | ",
        "Trang Sức Nam | ",
        "Kính Mắt Nam | ",
        "Thắt Lưng Nam | ",
        "Cà vạt & Nơ cổ | ",
        "Phụ Kiện Nam | ",
      ],
    },
    {
      title: "THỜI TRANG NU,",
      things: [
        "Áo Khoác | ",
        "Áo Vest và Blazer | ",
        "Áo Hoodie, Áo Len & Áo Nỉ | ",
        "Quần Jeans | ",
        "Quần Dài/Quần Âu | ",
        "Quần Short | ",
        "Áo | ",
        "Áo Ba Lỗ | ",
        "Đồ Lót | ",
        "Đồ Ngủ | ",
        "Đồ Bộ | ",
        "Vớ/Tất | ",
        "Trang Phục Truyền Thống | ",
        "Đồ Hóa Trang | ",
        "Trang Phục Ngành Nghề | ",
        "Khác | ",
        "Trang Sức Nam | ",
        "Kính Mắt Nam | ",
        "Thắt Lưng Nam | ",
        "Cà vạt & Nơ cổ | ",
        "Phụ Kiện Nam | ",
      ],
    },
    {
      title: "THỜI TRANG NU,",
      things: [
        "Áo Khoác | ",
        "Áo Vest và Blazer | ",
        "Áo Hoodie, Áo Len & Áo Nỉ | ",
        "Quần Jeans | ",
        "Quần Dài/Quần Âu | ",
        "Quần Short | ",
        "Áo | ",
        "Áo Ba Lỗ | ",
        "Đồ Lót | ",
        "Đồ Ngủ | ",
        "Đồ Bộ | ",
        "Vớ/Tất | ",
        "Trang Phục Truyền Thống | ",
        "Đồ Hóa Trang | ",
        "Trang Phục Ngành Nghề | ",
        "Khác | ",
        "Trang Sức Nam | ",
        "Kính Mắt Nam | ",
        "Thắt Lưng Nam | ",
        "Cà vạt & Nơ cổ | ",
        "Phụ Kiện Nam | ",
      ],
    },
    {
      title: "THỜI TRANG NU,",
      things: [
        "Áo Khoác | ",
        "Áo Vest và Blazer | ",
        "Áo Hoodie, Áo Len & Áo Nỉ | ",
        "Quần Jeans | ",
        "Quần Dài/Quần Âu | ",
        "Quần Short | ",
        "Áo | ",
        "Áo Ba Lỗ | ",
        "Đồ Lót | ",
        "Đồ Ngủ | ",
        "Đồ Bộ | ",
        "Vớ/Tất | ",
        "Trang Phục Truyền Thống | ",
        "Đồ Hóa Trang | ",
        "Trang Phục Ngành Nghề | ",
        "Khác | ",
        "Trang Sức Nam | ",
        "Kính Mắt Nam | ",
        "Thắt Lưng Nam | ",
        "Cà vạt & Nơ cổ | ",
        "Phụ Kiện Nam | ",
      ],
    },
    {
      title: "THỜI TRANG NAM,",
      things: [
        "Áo Khoác | ",
        "Áo Vest và Blazer | ",
        "Áo Hoodie, Áo Len & Áo Nỉ | ",
        "Quần Jeans | ",
        "Quần Dài/Quần Âu | ",
        "Quần Short | ",
        "Áo | ",
        "Áo Ba Lỗ | ",
        "Đồ Lót | ",
        "Đồ Ngủ | ",
        "Đồ Bộ | ",
        "Vớ/Tất | ",
        "Trang Phục Truyền Thống | ",
        "Đồ Hóa Trang | ",
        "Trang Phục Ngành Nghề | ",
        "Khác | ",
        "Trang Sức Nam | ",
        "Kính Mắt Nam | ",
        "Thắt Lưng Nam | ",
        "Cà vạt & Nơ cổ | ",
        "Phụ Kiện Nam | ",
      ],
    },
    {
      title: "THỜI TRANG NU,",
      things: [
        "Áo Khoác | ",
        "Áo Vest và Blazer | ",
        "Áo Hoodie, Áo Len & Áo Nỉ | ",
        "Quần Jeans | ",
        "Quần Dài/Quần Âu | ",
        "Quần Short | ",
        "Áo | ",
        "Áo Ba Lỗ | ",
        "Đồ Lót | ",
        "Đồ Ngủ | ",
        "Đồ Bộ | ",
        "Vớ/Tất | ",
        "Trang Phục Truyền Thống | ",
        "Đồ Hóa Trang | ",
        "Trang Phục Ngành Nghề | ",
        "Khác | ",
        "Trang Sức Nam | ",
        "Kính Mắt Nam | ",
        "Thắt Lưng Nam | ",
        "Cà vạt & Nơ cổ | ",
        "Phụ Kiện Nam | ",
      ],
    },
    {
      title: "THỜI TRANG NU,",
      things: [
        "Áo Khoác | ",
        "Áo Vest và Blazer | ",
        "Áo Hoodie, Áo Len & Áo Nỉ | ",
        "Quần Jeans | ",
        "Quần Dài/Quần Âu | ",
        "Quần Short | ",
        "Áo | ",
        "Áo Ba Lỗ | ",
        "Đồ Lót | ",
        "Đồ Ngủ | ",
        "Đồ Bộ | ",
        "Vớ/Tất | ",
        "Trang Phục Truyền Thống | ",
        "Đồ Hóa Trang | ",
        "Trang Phục Ngành Nghề | ",
        "Khác | ",
        "Trang Sức Nam | ",
        "Kính Mắt Nam | ",
        "Thắt Lưng Nam | ",
        "Cà vạt & Nơ cổ | ",
        "Phụ Kiện Nam | ",
      ],
    },
    {
      title: "THỜI TRANG NU,",
      things: [
        "Áo Khoác | ",
        "Áo Vest và Blazer | ",
        "Áo Hoodie, Áo Len & Áo Nỉ | ",
        "Quần Jeans | ",
        "Quần Dài/Quần Âu | ",
        "Quần Short | ",
        "Áo | ",
        "Áo Ba Lỗ | ",
        "Đồ Lót | ",
        "Đồ Ngủ | ",
        "Đồ Bộ | ",
        "Vớ/Tất | ",
        "Trang Phục Truyền Thống | ",
        "Đồ Hóa Trang | ",
        "Trang Phục Ngành Nghề | ",
        "Khác | ",
        "Trang Sức Nam | ",
        "Kính Mắt Nam | ",
        "Thắt Lưng Nam | ",
        "Cà vạt & Nơ cổ | ",
        "Phụ Kiện Nam | ",
      ],
    },
    {
      title: "THỜI TRANG NU,",
      things: [
        "Áo Khoác | ",
        "Áo Vest và Blazer | ",
        "Áo Hoodie, Áo Len & Áo Nỉ | ",
        "Quần Jeans | ",
        "Quần Dài/Quần Âu | ",
        "Quần Short | ",
        "Áo | ",
        "Áo Ba Lỗ | ",
        "Đồ Lót | ",
        "Đồ Ngủ | ",
        "Đồ Bộ | ",
        "Vớ/Tất | ",
        "Trang Phục Truyền Thống | ",
        "Đồ Hóa Trang | ",
        "Trang Phục Ngành Nghề | ",
        "Khác | ",
        "Trang Sức Nam | ",
        "Kính Mắt Nam | ",
        "Thắt Lưng Nam | ",
        "Cà vạt & Nơ cổ | ",
        "Phụ Kiện Nam | ",
      ],
    },
    {
      title: "THỜI TRANG NAM,",
      things: [
        "Áo Khoác | ",
        "Áo Vest và Blazer | ",
        "Áo Hoodie, Áo Len & Áo Nỉ | ",
        "Quần Jeans | ",
        "Quần Dài/Quần Âu | ",
        "Quần Short | ",
        "Áo | ",
        "Áo Ba Lỗ | ",
        "Đồ Lót | ",
        "Đồ Ngủ | ",
        "Đồ Bộ | ",
        "Vớ/Tất | ",
        "Trang Phục Truyền Thống | ",
        "Đồ Hóa Trang | ",
        "Trang Phục Ngành Nghề | ",
        "Khác | ",
        "Trang Sức Nam | ",
        "Kính Mắt Nam | ",
        "Thắt Lưng Nam | ",
        "Cà vạt & Nơ cổ | ",
        "Phụ Kiện Nam | ",
      ],
    },
    {
      title: "THỜI TRANG NU,",
      things: [
        "Áo Khoác | ",
        "Áo Vest và Blazer | ",
        "Áo Hoodie, Áo Len & Áo Nỉ | ",
        "Quần Jeans | ",
        "Quần Dài/Quần Âu | ",
        "Quần Short | ",
        "Áo | ",
        "Áo Ba Lỗ | ",
        "Đồ Lót | ",
        "Đồ Ngủ | ",
        "Đồ Bộ | ",
        "Vớ/Tất | ",
        "Trang Phục Truyền Thống | ",
        "Đồ Hóa Trang | ",
        "Trang Phục Ngành Nghề | ",
        "Khác | ",
        "Trang Sức Nam | ",
        "Kính Mắt Nam | ",
        "Thắt Lưng Nam | ",
        "Cà vạt & Nơ cổ | ",
        "Phụ Kiện Nam | ",
      ],
    },
    {
      title: "THỜI TRANG NU,",
      things: [
        "Áo Khoác | ",
        "Áo Vest và Blazer | ",
        "Áo Hoodie, Áo Len & Áo Nỉ | ",
        "Quần Jeans | ",
        "Quần Dài/Quần Âu | ",
        "Quần Short | ",
        "Áo | ",
        "Áo Ba Lỗ | ",
        "Đồ Lót | ",
        "Đồ Ngủ | ",
        "Đồ Bộ | ",
        "Vớ/Tất | ",
        "Trang Phục Truyền Thống | ",
        "Đồ Hóa Trang | ",
        "Trang Phục Ngành Nghề | ",
        "Khác | ",
        "Trang Sức Nam | ",
        "Kính Mắt Nam | ",
        "Thắt Lưng Nam | ",
        "Cà vạt & Nơ cổ | ",
        "Phụ Kiện Nam | ",
      ],
    },
    {
      title: "THỜI TRANG NU,",
      things: [
        "Áo Khoác | ",
        "Áo Vest và Blazer | ",
        "Áo Hoodie, Áo Len & Áo Nỉ | ",
        "Quần Jeans | ",
        "Quần Dài/Quần Âu | ",
        "Quần Short | ",
        "Áo | ",
        "Áo Ba Lỗ | ",
        "Đồ Lót | ",
        "Đồ Ngủ | ",
        "Đồ Bộ | ",
        "Vớ/Tất | ",
        "Trang Phục Truyền Thống | ",
        "Đồ Hóa Trang | ",
        "Trang Phục Ngành Nghề | ",
        "Khác | ",
        "Trang Sức Nam | ",
        "Kính Mắt Nam | ",
        "Thắt Lưng Nam | ",
        "Cà vạt & Nơ cổ | ",
        "Phụ Kiện Nam | ",
      ],
    },
    {
      title: "THỜI TRANG NU,",
      things: [
        "Áo Khoác | ",
        "Áo Vest và Blazer | ",
        "Áo Hoodie, Áo Len & Áo Nỉ | ",
        "Quần Jeans | ",
        "Quần Dài/Quần Âu | ",
        "Quần Short | ",
        "Áo | ",
        "Áo Ba Lỗ | ",
        "Đồ Lót | ",
        "Đồ Ngủ | ",
        "Đồ Bộ | ",
        "Vớ/Tất | ",
        "Trang Phục Truyền Thống | ",
        "Đồ Hóa Trang | ",
        "Trang Phục Ngành Nghề | ",
        "Khác | ",
        "Trang Sức Nam | ",
        "Kính Mắt Nam | ",
        "Thắt Lưng Nam | ",
        "Cà vạt & Nơ cổ | ",
        "Phụ Kiện Nam | ",
      ],
    },
  ],
};
const b = category.listCategory.map((item) => {
  return `
  <div class ="l-2-4 col  footer__category--list">
  <h3 class="footer__category--heading-item">${item.title}</h3>
  ${item.things
    .map((itemq, index) => {
      return `<a class="footer__category--item__link">${itemq}</a>`;
    })
    .join("")}    
  </div>`;
});
$(".footer__category--table").innerHTML = b.join("");

// handle

const index_product = $$(".home-product-item");

chuyentrang(index_product, "detail.html");
chuyentrang($$(".home-product-item--flashSales"), "detail.html");
chuyentrang($$(".category__container-item"), "category.html");

function chuyentrang(element, value) {
  element.forEach((item) => {
    item.href = value;
    item.onclick = () => {
      setconfig("searchvalue", "");
    };
  });
}
