function products() {
  var product = [
    {
      id: 1,
      name: "ÁO THUN NAM NGẮN TAY CỔ BẺ MẪU MỚI NHIỀU MÀU",
      img: "assests/img/clothes/1_1.jpg",
      oldPrice: "120.000",
      newPrice: "79.000",
      sold: "85,7K",
      address: "Hà Nội",
      saleOff: "34%",
      phobien: true,
      banchay: true,
      star: 4,
      favorite: true,
    },
    {
      id: 2,
      name: "quần âu nam mẫu mới nhiều màu",
      img: "assests/img/clothes/2_1.jpg",
      oldPrice: "820.000",
      newPrice: "599.000",
      sold: "5,7K",
      phobien: true,
      address: "Huế",
      saleOff: "23%",
      star: 5,
      favorite: true,
    },
    {
      id: 3,
      name: "Quần thể thao nam cao cấp chất mềm mịn ko nhăn nhiều màu HD76",
      img: "assests/img/clothes/2_4.jpg",
      oldPrice: "45.000",
      newPrice: "29.000",
      sold: "5,7K",
      address: "Huế",
      saleOff: "23%",
      star: 5,
      banchay: true,
      favorite: true,
    },
    {
      id: 4,
      name: "Tai nghe Bluetooth Không Dây AIP2 Pin Trâu- Cảm Ứng- Định Vị- Đổi Tên phụ kiện điện tử- Dùng Được Mọi Điện Thoại- Chính Hãng PKHN",
      img: "assests/img/phukien/s15.jpg",
      oldPrice: "150.000",
      newPrice: "50.000",
      sold: "4,7K",
      address: "Hồ chí minh",
      saleOff: "34%",
      banchay: true,
      star: 3,
    },

    {
      id: 5,
      name: "Bộ thun polo logo ngực form rộng tay lỡ phong cách trẻ trung năng động AO8",
      img: "assests/img/clothes/c1.jpg",
      oldPrice: "820.000",
      newPrice: "599.000",
      sold: "5,7K",
      banchay: true,
      address: "Hồ chí minh",
      saleOff: "23%",
      star: 5,
    },
    {
      id: 6,
      name: "Bộ 2 dây tay cách điệu, chất vải mềm mịm, phù hợp đi chơi đi biển, áo thời trang hot hè AO5",
      img: "assests/img/clothes/c2.jpg",
      oldPrice: "820.000",
      newPrice: "799.000",
      sold: "19,7K",
      phobien: true,
      banchay: true,
      address: "Hà Nội",
      saleOff: "23%",
      favorite: true,
      star: 5,
    },
    {
      id: 7,
      name: "áo thu đông dai",
      img: "assests/img/clothes/c3.jpg",
      oldPrice: "90.000",
      newPrice: "39.000",
      sold: "13,7K",
      address: "Huế",
      saleOff: "23%",
      star: 5,
    },
    {
      id: 8,
      name: "dây đeo thẻ sinh viên tiện lợi ",
      img: "assests/img/clothes/c4.jpg",
      oldPrice: "60.000",
      newPrice: "79.000",
      sold: "5,7K",
      banchay: true,
      address: "Hà Nội",
      saleOff: "23%",
      star: 5,
    },
    {
      id: 9,
      name: "Áo Khoác Thể Thao Nam Nữ Thun Poly dày dặn💗 Bo Cổ Chất Nỉ Đẹp",
      img: "assests/img/clothes/c5.jpg",
      oldPrice: "90.000",
      newPrice: "59.000",
      sold: "5,7K",
      address: "Huế",
      saleOff: "23%",
      phobien: true,
      star: 5,
      favorite: true,
    },
    {
      id: 10,
      name: "tất cao cổ nũ dài nhieu màu đẹp",
      img: "assests/img/clothes/c6.jpg",
      oldPrice: "10.000",
      newPrice: "9.000",
      sold: "43,7K",
      address: "Huế",
      saleOff: "23%",
      banchay: true,
      star: 5,
    },

    //
    {
      name: "Áo Xốp Nhăn Cổ Tròn - Áo Nữ Basic Phong Cách hàn Quốc Dễ Phối Đồ",
      img: "assests/img/product/sp1.jpeg",
      oldPrice: "",
      address: "Ngệ an",
      phobien: true,
      favorite: true,
      saleOff: "10%",
      newPrice: "50.000",
      sold: "6k",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      img: "./assests/img/product/sp2.jpeg",
      oldPrice: "",
      address: "Ngệ an",
      phobien: true,
      favorite: true,
      saleOff: "10%",
      newPrice: "50.000",
      sold: "6k",
    },
    {
      name: "Áo thun nam nữ-Áo phông tay lỡ Unisex ba màu Đen Trắng Xanh 3 Size M L XL",
      img: "./assests/img/product/sp3.jpeg",
      oldPrice: "",
      address: "Ngệ an",
      saleOff: "10%",
      newPrice: "50.000",
      sold: "6k",
    },
    {
      name: "Quần áo ống rộng nam nữ màu xanh phong cách unisex , quần baggy vải jeans không phai màu V12",
      img: "./assests/img/product/sp10.jpeg",
      oldPrice: "",
      address: "Ngệ an",
      saleOff: "10%",
      newPrice: "50.000",
      banchay: true,
      sold: "64k",
    },
    {
      name: "Quần jeans ống rộng nam nữ màu xanh phong cách unisex , quần baggy vải jeans không phai màu V12",
      img: "./assests/img/product/sp5.jpeg",
      oldPrice: "",
      address: "Ngệ an",
      saleOff: "10%",
      newPrice: "50.000",
      sold: "6k",
    },
    {
      name: "SOFT BOY - ÁO HOODIE",
      img: "./assests/img/product/sp6.jpeg",
      oldPrice: "",
      address: "Ngệ an",
      saleOff: "10%",
      newPrice: "50.000",
      sold: "6k",
      phobien: true,
      favorite: true,
    },
    {
      name: "Áo nữ thun gân form rộng tay lỡ basic dễ phối đồ AO2",
      img: "./assests/img/product/sp7.jpeg",
      oldPrice: "",
      address: "Ngệ an",
      saleOff: "10%",
      newPrice: "50.000",
      sold: "6k",
    },
    {
      name: "Điện Thoại Vsmart Joy 4 64GB Bảo Hành Chính Hãng Vsmart điện tử",
      img: "assests/img/phukien/s1.jpg",
      oldPrice: "300.000",
      address: "Hải phòng",
      saleOff: "20%",
      newPrice: "100.000",
      sold: "6k",
      phobien: true,
      favorite: true,
    },
    {
      name: "Điện thoại Samsung J2 Prime (G532) 2 Sim Hỗ trợ 4G LTE  giá rẻ ((Máy Cũ Hàng Chính Hãng) điện tử )",
      img: "assests/img/phukien/s2.jpg",
      oldPrice: "3.000.000",
      address: "Hải phòng",
      saleOff: "20%",
      newPrice: "1.000.000",
      sold: "6k",
    },
    {
      name: "[SALE] Điện thoại Asus Rog Phone 6 Gaming PRO 12GB|256GB - Hàng nhập khẩu - Bảo hành 12 tháng - Lỗi 1 đổi 1 điện tử",
      img: "assests/img/phukien/s3.jpg",
      oldPrice: "300.000",
      address: "Hải phòng",
      saleOff: "20%",
      newPrice: "100.000",
      sold: "6k",
      favorite: true,
      phobien: true,
    },
    {
      name: "loa kéo Bảo Hành Chính Hãng không đổi trả điện tử",
      img: "assests/img/phukien/s4.jpg",
      oldPrice: "300.000",
      address: "Hải phòng",
      saleOff: "20%",
      newPrice: "100.000",
      sold: "6k",
    },
  ];
  return product;
}
export default products;
